export const premiumProducts = [
  {
    id: 1,
    image: '/assets/_7d292370-0d52-48b9-bd58-125fb4ebea66.jpg',
    title: 'AlgoSeek CRM Pro',
    description: 'Advanced features and premium support included for enterprise customers.',
    fullDescription: 'Enterprise-grade CRM with advanced automation, custom workflows, and dedicated support. Includes priority bug fixes, feature requests, and onboarding assistance. Scales to thousands of users with enterprise security.',
    releaseDate: 'Feb 12, 2025',
    readTime: '6 min read',
    releaseLabel: 'Last Release - Feb 12, 2025',
    author: 'Algobasket',
    price: 29,
    license: 'Regular License',
    supportMonths: 6,
    recentlyUpdated: true,
  },
  {
    id: 2,
    image: '/assets/_ac27c117-f4ce-4fe1-b2fd-d55b3c7f790f.jpg',
    title: 'No-Code API Generator Pro',
    description: 'Enterprise-grade solutions with custom integrations and dedicated support.',
    fullDescription: 'Create unlimited APIs with advanced features. Includes custom connectors, webhooks, and API versioning. Enterprise support with SLA guarantee. Perfect for teams building internal tools or customer-facing APIs.',
    releaseDate: 'Jan 23, 2025',
    readTime: '4 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 49,
    license: 'Regular License',
    supportMonths: 6,
    recentlyUpdated: false,
  },
  {
    id: 3,
    image: '/assets/_845d11f3-6f93-45dc-85c9-f4a4469afe79.jpg',
    title: 'Real-Time Collaboration Suite Pro',
    description: 'Custom integrations and dedicated support for team workflows.',
    fullDescription: 'White-label collaboration platform with custom branding. Includes SSO, advanced permissions, and audit logs. Dedicated support for setup and customization. Deploy on-premise or in your cloud.',
    releaseDate: 'Feb 2, 2025',
    readTime: '10 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 79,
    license: 'Extended License',
    supportMonths: 6,
    recentlyUpdated: true,
  },
  {
    id: 4,
    image: '/assets/_7d292370-0d52-48b9-bd58-125fb4ebea66.jpg',
    title: 'Enterprise Analytics Pro',
    description: 'Advanced analytics with unlimited data sources and custom dashboards.',
    fullDescription: 'Unlimited data sources, custom dashboards, and scheduled reports. API access for embedding analytics. Role-based access control and compliance reporting. Includes priority support.',
    releaseDate: 'Feb 8, 2025',
    readTime: '7 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 59,
    license: 'Regular License',
    supportMonths: 6,
    recentlyUpdated: false,
  },
  {
    id: 5,
    image: '/assets/_ac27c117-f4ce-4fe1-b2fd-d55b3c7f790f.jpg',
    title: 'Premium API Gateway',
    description: 'High-performance API management with rate limiting and analytics.',
    fullDescription: 'Manage, rate-limit, and monitor all your APIs from one dashboard. Includes API analytics, caching, and transformation. Supports OAuth, API keys, and custom authentication. Built for high traffic.',
    releaseDate: 'Jan 30, 2025',
    readTime: '5 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 39,
    license: 'Regular License',
    supportMonths: 6,
    recentlyUpdated: true,
  },
  {
    id: 6,
    image: '/assets/_845d11f3-6f93-45dc-85c9-f4a4469afe79.jpg',
    title: 'White-Label Collaboration Suite',
    description: 'Fully customizable collaboration platform with your branding.',
    fullDescription: 'Rebrand the entire platform with your logo, colors, and domain. Remove all Algobasket branding. Includes custom email templates and support portal. Perfect for agencies and resellers.',
    releaseDate: 'Feb 10, 2025',
    readTime: '9 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 99,
    license: 'Extended License',
    supportMonths: 12,
    recentlyUpdated: false,
  },
]
