export const nicheProducts = [
  {
    id: 1,
    image: '/assets/_7d292370-0d52-48b9-bd58-125fb4ebea66.jpg',
    title: 'AlgoSeek CRM',
    description: 'A Smart, Open-Source, AI-Powered CRM for Modern Businesses',
    fullDescription: 'AlgoSeek CRM is a comprehensive customer relationship management solution designed for modern businesses. It offers AI-powered insights, contact management, sales pipeline tracking, and seamless integration with popular tools. Perfect for startups and growing teams looking to streamline their sales and customer management processes.',
    releaseDate: 'Feb 12, 2025',
    readTime: '6 min read',
    releaseLabel: 'Last Release - Feb 12, 2025',
    author: 'Algobasket',
    price: 0,
    license: 'Free',
    supportMonths: 6,
    recentlyUpdated: true,
  },
  {
    id: 2,
    image: '/assets/_ac27c117-f4ce-4fe1-b2fd-d55b3c7f790f.jpg',
    title: 'No-Code API Generator',
    description: 'An open-source tool that lets users create custom APIs without coding, using an intuitive drag-and-drop interface.',
    fullDescription: 'Create custom APIs without writing a single line of code. Our drag-and-drop interface lets you design, test, and deploy APIs in minutes. Supports REST and GraphQL, with built-in authentication and rate limiting. Ideal for rapid prototyping and citizen developers.',
    releaseDate: 'Jan 23, 2025',
    readTime: '4 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 0,
    license: 'Free',
    supportMonths: 6,
    recentlyUpdated: false,
  },
  {
    id: 3,
    image: '/assets/_845d11f3-6f93-45dc-85c9-f4a4469afe79.jpg',
    title: 'Real-Time Collaboration Suite',
    description: 'An open-source platform for seamless, real-time document editing, team chat, and file sharing.',
    fullDescription: 'Collaborate in real-time with your team. Features include live document editing, team chat, file sharing, and video calls. All data is encrypted and you can self-host for full control. Compatible with popular formats and integrates with your existing tools.',
    releaseDate: 'Feb 2, 2025',
    readTime: '10 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 0,
    license: 'Free',
    supportMonths: 6,
    recentlyUpdated: true,
  },
  {
    id: 4,
    image: '/assets/_7d292370-0d52-48b9-bd58-125fb4ebea66.jpg',
    title: 'Niche Analytics Dashboard',
    description: 'Specialized analytics for niche markets with custom reporting and insights.',
    fullDescription: 'Get deep insights into your niche market with custom dashboards and reports. Track KPIs, trends, and competitor performance. Export data to CSV or connect to your BI tools. Supports multiple data sources and real-time updates.',
    releaseDate: 'Jan 15, 2025',
    readTime: '5 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 0,
    license: 'Free',
    supportMonths: 6,
    recentlyUpdated: false,
  },
  {
    id: 5,
    image: '/assets/_ac27c117-f4ce-4fe1-b2fd-d55b3c7f790f.jpg',
    title: 'Vertical Market Toolkit',
    description: 'Pre-built tools and templates for vertical market solutions.',
    fullDescription: 'Accelerate your vertical market development with pre-built templates, components, and workflows. Covers healthcare, retail, education, and more. Includes compliance checklists, best practices, and integration guides.',
    releaseDate: 'Feb 5, 2025',
    readTime: '6 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 0,
    license: 'Free',
    supportMonths: 6,
    recentlyUpdated: true,
  },
  {
    id: 6,
    image: '/assets/_845d11f3-6f93-45dc-85c9-f4a4469afe79.jpg',
    title: 'Sector-Specific CRM',
    description: 'Tailored CRM features for healthcare, education, and retail sectors.',
    fullDescription: 'CRM built for your industry. Healthcare module includes HIPAA compliance, patient scheduling, and referral tracking. Education module supports student management and parent portals. Retail module handles inventory and loyalty programs.',
    releaseDate: 'Jan 28, 2025',
    readTime: '8 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 0,
    license: 'Free',
    supportMonths: 6,
    recentlyUpdated: false,
  },
]
