export const cryptoProducts = [
  {
    id: 1,
    image: '/assets/_7d292370-0d52-48b9-bd58-125fb4ebea66.jpg',
    title: 'Crypto Portfolio Tracker',
    description: 'Track your crypto holdings across multiple wallets and exchanges in one dashboard.',
    fullDescription: 'Monitor your entire crypto portfolio in real-time. Supports 500+ coins, multiple wallets, and exchange integrations. Get price alerts, performance analytics, and tax-ready reports. Secure and privacy-focused with optional self-hosting.',
    releaseDate: 'Feb 12, 2025',
    readTime: '5 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 29,
    license: 'Regular License',
    supportMonths: 6,
    recentlyUpdated: true,
  },
  {
    id: 2,
    image: '/assets/_ac27c117-f4ce-4fe1-b2fd-d55b3c7f790f.jpg',
    title: 'DeFi Analytics Suite',
    description: 'Analyze DeFi protocols, yield opportunities, and on-chain metrics.',
    fullDescription: 'Comprehensive DeFi analytics for yield farming, liquidity pools, and protocol health. Track TVL, APY, impermanent loss, and gas costs. Integrates with major chains including Ethereum, BSC, and Polygon.',
    releaseDate: 'Jan 30, 2025',
    readTime: '6 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 49,
    license: 'Regular License',
    supportMonths: 6,
    recentlyUpdated: false,
  },
  {
    id: 3,
    image: '/assets/_845d11f3-6f93-45dc-85c9-f4a4469afe79.jpg',
    title: 'NFT Marketplace Kit',
    description: 'Launch your own NFT marketplace with minting, trading, and royalty features.',
    fullDescription: 'Complete NFT marketplace solution with minting, auctions, fixed-price listings, and royalty splits. Multi-chain support, wallet integration, and admin dashboard. White-label ready for your brand.',
    releaseDate: 'Feb 5, 2025',
    readTime: '8 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 79,
    license: 'Extended License',
    supportMonths: 12,
    recentlyUpdated: true,
  },
]
