export const aiProducts = [
  {
    id: 1,
    image: '/assets/_7d292370-0d52-48b9-bd58-125fb4ebea66.jpg',
    title: 'AI Content Generator',
    description: 'Generate high-quality content with advanced AI models for blogs, social media, and marketing.',
    fullDescription: 'AI Content Generator leverages state-of-the-art language models to create engaging content across multiple formats. Supports multiple languages, tone adjustment, and SEO optimization. Perfect for content creators, marketers, and businesses looking to scale their content production.',
    releaseDate: 'Feb 15, 2025',
    readTime: '5 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 19,
    license: 'Regular License',
    supportMonths: 6,
    recentlyUpdated: true,
  },
  {
    id: 2,
    image: '/assets/_ac27c117-f4ce-4fe1-b2fd-d55b3c7f790f.jpg',
    title: 'AI Chatbot Builder',
    description: 'Build custom AI chatbots for customer support, lead generation, and automation.',
    fullDescription: 'Create intelligent chatbots without coding. Train on your data, integrate with your tools, and deploy in minutes. Supports voice, text, and multi-language. Includes analytics dashboard and A/B testing for continuous improvement.',
    releaseDate: 'Jan 28, 2025',
    readTime: '6 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 39,
    license: 'Regular License',
    supportMonths: 6,
    recentlyUpdated: false,
  },
  {
    id: 3,
    image: '/assets/_845d11f3-6f93-45dc-85c9-f4a4469afe79.jpg',
    title: 'AI Image & Video Tools',
    description: 'AI-powered image generation, enhancement, and video editing for creative professionals.',
    fullDescription: 'Generate stunning images from text prompts, upscale low-resolution photos, remove backgrounds, and apply AI-powered video effects. Supports batch processing and API access for integration into your workflows.',
    releaseDate: 'Feb 10, 2025',
    readTime: '7 min read',
    releaseLabel: 'Last Release',
    author: 'Algobasket',
    price: 49,
    license: 'Extended License',
    supportMonths: 6,
    recentlyUpdated: true,
  },
]
